FROM schoolofdevops/centos-node:v1.1
MAINTAINER babu <babu@initcron.org>

LABEL env=des


COPY motd.sh /opt/

RUN chmod +x /opt/motd.sh && \
    sh /opt/motd.sh && \
    rm -rf /opt/motd.sh

COPY authorized_keys /home/devops/.ssh/authorized_keys

EXPOSE 22
CMD ["/bin/bash","/bootstrap.sh"]




